- name: build cli @quick
  run: make build
  change: "**/*.go"
  run_on_init: true

- name: run ci checks @quick @ci
  run: | ## Watch with `fzz -t @ci`
   cat .github/workflows/on-push.yml \
    | yq '.jobs | .[] | .steps | .[] | .run | select(. != null)' \
    | xargs -I {} bash -c {}
  change:
    - "**/*.go"
    - "**/*.snap"
  run_on_init: true

- name: git stage file @quick
  run: git add {{relative_path}}
  change: 
    - "**/*.go"
    - "**/*.snap"
  run_on_init: true
