package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/cristianoliveira/sway-setter/internal/parser"
	"github.com/cristianoliveira/sway-setter/internal/sway"
	"github.com/spf13/cobra"
)

func OutputCmd() *cobra.Command {
	// sway-setter outputs
	return &cobra.Command{
		Use:   "outputs <stdin>",
		Short: "Set outputs from stdin - Use: `swaymsg -t get_outputs`",
		RunE: func(cmd *cobra.Command, args []string) error {
			flagPrint, err := cmd.Flags().GetBool("print")
			if flagPrint {
				sway.ConfigStdoutConnector()
			}

			swaymsg, err := sway.ConnectToSway()
			if err != nil {
				return err
			}

			input, err := ScanStdin()
			if err != nil {
				return err
			}

			var outputs []parser.SwayOutput
			err = json.Unmarshal([]byte(input), &outputs)
			if err != nil {
				return fmt.Errorf("Error: failed to parse input content\nHint: make sure to use a file generated by the `swaymsg -t get_outputs` output")
			}

			commands, err := parser.SetOutputsCommand(outputs)
			if err != nil {
				return err
			}

			err = swaymsg.Commands(commands)
			if err != nil {
				return err
			}

			return nil
		},
	}
}
