package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/cristianoliveira/sway-setter/internal/parser"
	"github.com/cristianoliveira/sway-setter/internal/sway"
	"github.com/spf13/cobra"
)

func WorkspacesCmd() *cobra.Command {
	// sway-setter workspaces < workspaces.json
	return &cobra.Command{
		Use:   "workspaces <stdin>",
		Short: "Set workspaces from stdin - Use: `swaymsg -t get_workspaces`",
		RunE: func(cmd *cobra.Command, args []string) error {
			flagPrint, err := cmd.Flags().GetBool("print")
			if flagPrint {
				sway.ConfigStdoutConnector()
			}

			swaymsg, err := sway.ConnectToSway()
			if err != nil {
				return err
			}

			input, err := ScanStdin()
			if err != nil {
				return err
			}

			var workspaces []parser.SwayWorkspace
			err = json.Unmarshal([]byte(input), &workspaces)
			if err != nil {
				return fmt.Errorf("Error: failed to parse input content\nHint: make sure to use a file generated by the `swaymsg -t get_workspaces` output")
			}

			commands, err := parser.SetWorkspacesCommand(workspaces)
			if err != nil {
				return err
			}

			err = swaymsg.Commands(commands)
			if err != nil {
				return err
			}

			return nil
		},
	}
}
