package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"

	"github.com/cristianoliveira/sway-setter/internal/setters"
	"github.com/jessevdk/go-flags"
)

func main() {
	var opts struct {
		Type  string `short:"t" long:"type" description:"Type 'set_{type}' object to be set analog of 'swaymsg -t get_{type}'"`
		Print bool   `short:"p" long:"print" description:"Prints commands that would be executed. Can be used as input to swaymsg"`
	}

	args := os.Args[1:]
	args, err := flags.ParseArgs(&opts, args)
	if err != nil {
		if len(os.Args) <= 1 {
			os.Exit(1)
		} else {
			os.Exit(0)
		}
		return
	}

	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Err() != nil {
		fmt.Println("Error: failed to read input")
		fmt.Println(err)
		os.Exit(1)
	}

	if opts.Print {
		setters.ConfigureStdout()
	}

	if len(opts.Type) > 0 {
		if opts.Type == "set_workspaces" {
			input := ""
			for scanner.Scan() {
				input += scanner.Text() + "\n"
			}

			if len(input) == 0 {
				fmt.Println("No input provided")
				os.Exit(1)
			}

			var workspaces []setters.SwayWorkspace
			err = json.Unmarshal([]byte(input), &workspaces)
			if err != nil {
				fmt.Println("Error: failed to parse input content")
				fmt.Println("Hint: make sure to use a file generated by the `swaymsg -t get_workspaces` output")

				os.Exit(1)
			}
			setters.SetWorkspaces(workspaces)
			return
		}

		fmt.Printf("Error: type `%s` is not supported\n", opts.Type)
		fmt.Println("Supported types")
		fmt.Println(" set_workspaces: load workspaces from `swaymsg` output")
		os.Exit(1)
	}

	flags.ParseArgs(&opts, []string{"-h"})
	os.Exit(0)
}
